FROM jenkins:2.19.4
MAINTAINER Moti Abudi
#
USER root
RUN mkdir /var/log/jenkins
RUN mkdir /var/cache/jenkins
RUN chown -R jenkins:jenkins /var/log/jenkins
RUN chown -R jenkins:jenkins /var/cache/jenkins
#
USER jenkins
#Set Defaults
#ENV JAVA_OPTS="-Xmx1096m"
ENV JENKINS_OPTS=”--handlerCountStartup=100 -handlerCountMax=300 --logfile=/var/log/jenkins/jenkins.log -webroot=/var/cache/jenkins/war”

